# NOTE: Ideally, this config file should use `build.commands`.
# However, as it does not support `build.apt_packages` we cannot install the dependencies required to generate the screenshots.
# For now, we are using `build.jobs` as a workaround to see how it works.
# Check https://github.com/readthedocs/readthedocs.org/issues/9599

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - libasound2
    - libdbus-glib-1-2
  jobs:
    post_install:
      - pip install nox
      - nox -s publish
    pre_build:
      - mkdir -p docs/_templates/ docs/_build/html
      - cp public/index.html docs/_templates
      - cp -r public/* docs/_build/html/

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: docs/conf.py
