version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    - pip install nox
    - nox -s publish
    - mkdir -p _readthedocs/html/
    - mv public/ _readthedocs/html/public/

  # playwright install-deps firefox
  # We can't call it like that because it needs sudo permissions
  # https://github.com/microsoft/playwright/blob/a2e8c17fbf8f9109c910cfbfcf2092bb35f0d867/packages/playwright-core/src/server/registry/nativeDeps.ts#L476
  apt_packages:
    - ffmpeg
    - libasound2
    - libatk1.0-0
    - libcairo-gobject2
    - libcairo2
    - libdbus-1-3
    - libdbus-glib-1-2
    - libfontconfig1
    - libfreetype6
    - libgdk-pixbuf-2.0-0
    - libglib2.0-0
    - libgtk-3-0
    - libpango-1.0-0
    - libpangocairo-1.0-0
    - libx11-6
    - libx11-xcb1
    - libxcb-shm0
    - libxcb1
    - libxcomposite1
    - libxcursor1
    - libxdamage1
    - libxext6
    - libxfixes3
    - libxi6
    - libxrandr2
    - libxrender1
    - libxtst6
